/coc/flash12/ywang4138/ERDiff/scripts/mla.py:82: DeprecationWarning: Importing gaussian from 'scipy.signal' is deprecated since SciPy 1.1.0 and will raise an error in SciPy 1.13.0. Please use 'scipy.signal.windows.gaussian' or the convenience function 'scipy.signal.get_window' instead.
  window = signal.gaussian(kern_sd, kern_sd, sym=True)
/srv/wu-lab/flash12/ywang4138/anaconda3/envs/yule-dv/lib/python3.11/site-packages/torch/nn/modules/transformer.py:307: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: 1220734650 (1220734650-georgia-institute-of-technology). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.18.7
wandb: Run data is saved locally in /coc/flash12/ywang4138/ERDiff/scripts/wandb/run-20250308_194902-wrktfb0j
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run ERDiff_MLA_0308_1949
wandb: ‚≠êÔ∏è View project at https://wandb.ai/1220734650-georgia-institute-of-technology/ERDiff_MLA
wandb: üöÄ View run at https://wandb.ai/1220734650-georgia-institute-of-technology/ERDiff_MLA/runs/wrktfb0j
--- Logging error ---
Traceback (most recent call last):
  File "/srv/wu-lab/flash12/ywang4138/anaconda3/envs/yule-dv/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/wu-lab/flash12/ywang4138/anaconda3/envs/yule-dv/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/wu-lab/flash12/ywang4138/anaconda3/envs/yule-dv/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/wu-lab/flash12/ywang4138/anaconda3/envs/yule-dv/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 68, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/srv/wu-lab/flash12/ywang4138/anaconda3/envs/yule-dv/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError
wandb.sdk.interface.router.MessageRouterClosedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/wu-lab/flash12/ywang4138/anaconda3/envs/yule-dv/lib/python3.11/logging/__init__.py", line 1114, in emit
    self.flush()
  File "/srv/wu-lab/flash12/ywang4138/anaconda3/envs/yule-dv/lib/python3.11/logging/__init__.py", line 1094, in flush
    self.stream.flush()
OSError: [Errno 116] Stale file handle
Call stack:
  File "/srv/wu-lab/flash12/ywang4138/anaconda3/envs/yule-dv/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/srv/wu-lab/flash12/ywang4138/anaconda3/envs/yule-dv/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/srv/wu-lab/flash12/ywang4138/anaconda3/envs/yule-dv/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/srv/wu-lab/flash12/ywang4138/anaconda3/envs/yule-dv/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 75, in message_loop
    logger.warning("message_loop has been closed")
Message: 'message_loop has been closed'
Arguments: ()
